import { createWorkspaceBindings } from "./workspaceBindings.js";
import { feedbackFilterOptions } from "./feedbackFilters.js";
import {
  auditCandidateCount,
  auditChunkLabel,
  auditFilteredCount,
  auditInactiveFilteredCount,
  auditKeptCount,
  auditOlderVersionFilteredCount,
  auditSourceGroups,
  evalRowStatus,
  evalRowStatusLabel,
  evalRowTitle,
  failureReasonEntries,
  feedbackTypeLabel,
  formatAuditScope,
  formatDepartments,
  formatFailureReason,
  formatFileSize,
  formatLifecycle,
  formatNumber,
  formatOperationLabel,
  formatPageRange,
  formatPercent,
  formatRagFeature,
  formatScore,
  formatScopeLabel,
  formatSourceName,
  formatStatusCount,
  formatStructureLocation,
  formatUsageBucket,
  formatUsageEventDetail,
  hasSources,
  isRetrievalOnlyReport,
  lifecycleClass,
} from "./formatters.js";
import { feedbackOptions, formatDate } from "./uiHelpers.js";

export function createAppWorkspaceBindings({ state, modelUsage, adminData, chat, knowledge, users, feedback, navigation }) {
  return createWorkspaceBindings({
    refs: { ...state, ...modelUsage },
    values: { pageSize: state.pageSize },
    actions: {
      openNewChat: chat.openNewChat,
      openConversation: chat.openConversation,
      sendMessageStream: chat.sendMessageStream,
      submitFeedback: feedback.submitFeedback,
      syncEnabledKnowledgeSources: knowledge.syncEnabledKnowledgeSources,
      clearMissingKnowledgeFiles: knowledge.clearMissingKnowledgeFiles,
      ragStatusClass: adminData.ragStatusClass,
      acknowledgeFailedIndexJobs: adminData.acknowledgeFailedIndexJobs,
      setKnowledgeTab: navigation.setKnowledgeTab,
      uploadKnowledgeFile: knowledge.uploadKnowledgeFile,
      onKnowledgeFileChange: knowledge.onKnowledgeFileChange,
      searchKnowledge: knowledge.searchKnowledge,
      defaultKnowledgeMinScore: knowledge.defaultKnowledgeMinScore,
      deleteKnowledgeDocument: knowledge.deleteKnowledgeDocument,
      runRagEval: adminData.runRagEval,
      loadRagEval: adminData.loadRagEval,
      setModelUsagePeriod: navigation.setModelUsagePeriod,
      setUsageTrendTab: navigation.setUsageTrendTab,
      modelUsageTrendRows: modelUsage.modelUsageTrendRows,
      modelUsageTrendBarSegments: modelUsage.modelUsageTrendBarSegments,
      showUsageTrendTooltip: modelUsage.showUsageTrendTooltip,
      hideUsageTrendTooltip: modelUsage.hideUsageTrendTooltip,
      modelUsageTrendAxisTicks: modelUsage.modelUsageTrendAxisTicks,
      modelUsageTrendAxisTickStyle: modelUsage.modelUsageTrendAxisTickStyle,
      modelUsageTrendSeries: modelUsage.modelUsageTrendSeries,
      modelUsageRecentEvents: modelUsage.modelUsageRecentEvents,
      modelUsageTotalTokens: modelUsage.modelUsageTotalTokens,
      setUsageEventsPage: navigation.setUsageEventsPage,
      setUsersTab: navigation.setUsersTab,
      createUserAccount: users.createUserAccount,
      userEditChanged: users.userEditChanged,
      saveUserAccount: users.saveUserAccount,
      createDepartmentItem: users.createDepartmentItem,
      deleteDepartmentItem: users.deleteDepartmentItem,
      openOperationsOverview: navigation.openOperationsOverview,
      openMissingDocManagement: navigation.openMissingDocManagement,
      setOperationsTab: navigation.setOperationsTab,
      loadRagFeedback: adminData.loadRagFeedback,
      setFeedbackPage: navigation.setFeedbackPage,
      setFeedbackTypeFilter: navigation.setFeedbackTypeFilter,
      loadKnowledgeAudits: adminData.loadKnowledgeAudits,
      setAuditPage: navigation.setAuditPage,
      setMissingDocPage: navigation.setMissingDocPage,
    },
    helpers: {
      feedbackOptions,
      feedbackTypeLabel,
      feedbackFilterOptions,
      hasSources,
      formatDate,
      formatSourceName,
      formatScore,
      formatPageRange,
      formatStatusCount,
      formatRagFeature,
      formatStructureLocation,
      formatFileSize,
      lifecycleClass,
      formatLifecycle,
      isRetrievalOnlyReport,
      formatPercent,
      failureReasonEntries,
      formatFailureReason,
      evalRowStatus,
      evalRowTitle,
      evalRowStatusLabel,
      formatNumber,
      formatUsageTrendBucket: modelUsage.formatUsageTrendBucket,
      formatUsageTrendAxisBucket: modelUsage.formatUsageTrendAxisBucket,
      formatUsageBucket,
      formatOperationLabel,
      formatScopeLabel,
      formatUsageEventDetail,
      formatDepartments,
      formatAuditScope,
      auditCandidateCount,
      auditKeptCount,
      auditFilteredCount,
      auditInactiveFilteredCount,
      auditOlderVersionFilteredCount,
      auditSourceGroups,
      auditChunkLabel,
    },
  });
}
