<script setup>
import ChatView from "../components/ChatView.vue";
import ConversationSidebar from "../components/ConversationSidebar.vue";
import KnowledgePage from "./KnowledgePage.vue";
import OperationsPage from "./OperationsPage.vue";
import TokenMonitorPage from "./TokenMonitorPage.vue";
import UsersPage from "./UsersPage.vue";

defineProps({
  b: { type: Object, required: true },
});
</script>

<template>
  <div class="workspace">
    <ConversationSidebar
      :conversations="b.conversations"
      :current-conversation-id="b.currentConversationId"
      :format-date="b.formatDate"
      @new-chat="b.openNewChat"
      @open-conversation="b.openConversation"
    />

    <ChatView
      v-if="b.activeView === 'chat'"
      :ref="(view) => { b.chatView.value = view; }"
      v-model:input="b.input"
      :conversation-loading="b.conversationLoading"
      :messages="b.messages"
      :error="b.error"
      :loading="b.loading"
      :feedback-options="b.feedbackOptions"
      :feedback-type-label="b.feedbackTypeLabel"
      :has-sources="b.hasSources"
      :format-date="b.formatDate"
      :format-source-name="b.formatSourceName"
      :format-score="b.formatScore"
      :format-page-range="b.formatPageRange"
      @send="b.sendMessageStream"
      @submit-feedback="b.submitFeedback"
    />

    <KnowledgePage
      v-else-if="b.isAdmin && b.activeView === 'knowledge'"
      :knowledge-loading="b.knowledgeLoading"
      :knowledge-documents="b.knowledgeDocuments"
      :has-enabled-knowledge-sources="b.hasEnabledKnowledgeSources"
      :rag-status="b.ragStatus"
      :rag-status-error="b.ragStatusError"
      :failed-index-jobs-expanded="b.failedIndexJobsExpanded"
      :acknowledging-failed-jobs="b.acknowledgingFailedJobs"
      :knowledge-tab="b.knowledgeTab"
      :selected-knowledge-file="b.selectedKnowledgeFile"
      :knowledge-notes="b.knowledgeNotes"
      :knowledge-department="b.knowledgeDepartment"
      :departments="b.departments"
      :knowledge-error="b.knowledgeError"
      :knowledge-index-job="b.knowledgeIndexJob"
      :knowledge-search-query="b.knowledgeSearchQuery"
      :knowledge-search-loading="b.knowledgeSearchLoading"
      :knowledge-search-error="b.knowledgeSearchError"
      :knowledge-search-results="b.knowledgeSearchResults"
      :rag-eval-suites="b.ragEvalSuites"
      :selected-rag-eval-suite="b.selectedRagEvalSuite"
      :selected-rag-eval-suite-info="b.selectedRagEvalSuiteInfo"
      :rag-eval-running="b.ragEvalRunning"
      :rag-eval-loading="b.ragEvalLoading"
      :rag-eval-error="b.ragEvalError"
      :rag-eval="b.ragEval"
      :sync-enabled-knowledge-sources="b.syncEnabledKnowledgeSources"
      :clear-missing-knowledge-files="b.clearMissingKnowledgeFiles"
      :format-status-count="b.formatStatusCount"
      :rag-status-class="b.ragStatusClass"
      :format-rag-feature="b.formatRagFeature"
      :acknowledge-failed-index-jobs="b.acknowledgeFailedIndexJobs"
      :format-date="b.formatDate"
      :set-knowledge-tab="b.setKnowledgeTab"
      :upload-knowledge-file="b.uploadKnowledgeFile"
      :on-knowledge-file-change="b.onKnowledgeFileChange"
      :search-knowledge="b.searchKnowledge"
      :default-knowledge-min-score="b.defaultKnowledgeMinScore"
      :format-source-name="b.formatSourceName"
      :format-page-range="b.formatPageRange"
      :format-structure-location="b.formatStructureLocation"
      :format-score="b.formatScore"
      :format-file-size="b.formatFileSize"
      :lifecycle-class="b.lifecycleClass"
      :format-lifecycle="b.formatLifecycle"
      :delete-knowledge-document="b.deleteKnowledgeDocument"
      :run-rag-eval="b.runRagEval"
      :load-rag-eval="b.loadRagEval"
      :is-retrieval-only-report="b.isRetrievalOnlyReport"
      :format-percent="b.formatPercent"
      :failure-reason-entries="b.failureReasonEntries"
      :format-failure-reason="b.formatFailureReason"
      :eval-row-status="b.evalRowStatus"
      :eval-row-title="b.evalRowTitle"
      :eval-row-status-label="b.evalRowStatusLabel"
      @update:failed-index-jobs-expanded="b.failedIndexJobsExpanded = $event"
      @update:selected-knowledge-file="b.selectedKnowledgeFile = $event"
      @update:knowledge-notes="b.knowledgeNotes = $event"
      @update:knowledge-department="b.knowledgeDepartment = $event"
      @update:knowledge-search-query="b.knowledgeSearchQuery = $event"
      @update:selected-rag-eval-suite="b.selectedRagEvalSuite = $event"
    />

    <TokenMonitorPage
      v-else-if="b.isAdmin && b.activeView === 'token-monitor'"
      :model-usage-period="b.modelUsagePeriod"
      :model-usage-error="b.modelUsageError"
      :usage-trend-tab="b.usageTrendTab"
      :usage-trend-tooltip="b.usageTrendTooltip"
      :page-size="b.pageSize"
      :usage-events-page="b.usageEventsPage"
      :usage-events-total-pages="b.usageEventsTotalPages"
      :paged-model-usage-events="b.pagedModelUsageEvents"
      :set-model-usage-period="b.setModelUsagePeriod"
      :set-usage-trend-tab="b.setUsageTrendTab"
      :model-usage-trend-rows="b.modelUsageTrendRows"
      :model-usage-trend-bar-segments="b.modelUsageTrendBarSegments"
      :show-usage-trend-tooltip="b.showUsageTrendTooltip"
      :hide-usage-trend-tooltip="b.hideUsageTrendTooltip"
      :format-number="b.formatNumber"
      :format-usage-trend-bucket="b.formatUsageTrendBucket"
      :model-usage-trend-axis-ticks="b.modelUsageTrendAxisTicks"
      :model-usage-trend-axis-tick-style="b.modelUsageTrendAxisTickStyle"
      :format-usage-trend-axis-bucket="b.formatUsageTrendAxisBucket"
      :model-usage-trend-series="b.modelUsageTrendSeries"
      :model-usage-recent-events="b.modelUsageRecentEvents"
      :format-usage-bucket="b.formatUsageBucket"
      :format-operation-label="b.formatOperationLabel"
      :format-scope-label="b.formatScopeLabel"
      :model-usage-total-tokens="b.modelUsageTotalTokens"
      :format-usage-event-detail="b.formatUsageEventDetail"
      :set-usage-events-page="b.setUsageEventsPage"
    />

    <UsersPage
      v-else-if="b.isAdmin && b.activeView === 'users'"
      :users-tab="b.usersTab"
      :set-users-tab="b.setUsersTab"
      :new-user-username="b.newUserUsername"
      :new-user-password="b.newUserPassword"
      :new-user-role="b.newUserRole"
      :new-user-department="b.newUserDepartment"
      :departments="b.departments"
      :users-loading="b.usersLoading"
      :users-error="b.usersError"
      :users="b.users"
      :user-edits="b.userEdits"
      :departments-loading="b.departmentsLoading"
      :departments-error="b.departmentsError"
      :new-department-name="b.newDepartmentName"
      :create-user-account="b.createUserAccount"
      :user-edit-changed="b.userEditChanged"
      :save-user-account="b.saveUserAccount"
      :create-department-item="b.createDepartmentItem"
      :delete-department-item="b.deleteDepartmentItem"
      :format-date="b.formatDate"
      :format-departments="b.formatDepartments"
      @update:new-user-username="b.newUserUsername = $event"
      @update:new-user-password="b.newUserPassword = $event"
      @update:new-user-role="b.newUserRole = $event"
      @update:new-user-department="b.newUserDepartment = $event"
      @update:new-department-name="b.newDepartmentName = $event"
    />

    <OperationsPage
      v-else-if="b.isAdmin && b.activeView === 'operations'"
      :operations-view="b.operationsView"
      :operations-tab="b.operationsTab"
      :feedback-loading="b.feedbackLoading"
      :feedback-error="b.feedbackError"
      :selected-feedback-type="b.selectedFeedbackType"
      :rag-feedback-summary="b.ragFeedbackSummary"
      :rag-feedback="b.ragFeedback"
      :filtered-rag-feedback="b.filteredRagFeedback"
      :paged-rag-feedback="b.pagedRagFeedback"
      :page-size="b.pageSize"
      :feedback-page="b.feedbackPage"
      :feedback-total-pages="b.feedbackTotalPages"
      :audit-loading="b.auditLoading"
      :audit-error="b.auditError"
      :paged-knowledge-audits="b.pagedKnowledgeAudits"
      :knowledge-audits="b.knowledgeAudits"
      :audit-page="b.auditPage"
      :audit-total-pages="b.auditTotalPages"
      :missing-doc-feedback="b.missingDocFeedback"
      :paged-missing-doc-feedback="b.pagedMissingDocFeedback"
      :missing-doc-page="b.missingDocPage"
      :missing-doc-total-pages="b.missingDocTotalPages"
      :open-operations-overview="b.openOperationsOverview"
      :open-missing-doc-management="b.openMissingDocManagement"
      :set-operations-tab="b.setOperationsTab"
      :load-rag-feedback="b.loadRagFeedback"
      :set-feedback-page="b.setFeedbackPage"
      :set-feedback-type-filter="b.setFeedbackTypeFilter"
      :load-knowledge-audits="b.loadKnowledgeAudits"
      :set-audit-page="b.setAuditPage"
      :set-missing-doc-page="b.setMissingDocPage"
      :feedback-type-label="b.feedbackTypeLabel"
      :feedback-filter-options="b.feedbackFilterOptions"
      :format-date="b.formatDate"
      :format-source-name="b.formatSourceName"
      :format-departments="b.formatDepartments"
      :format-audit-scope="b.formatAuditScope"
      :audit-candidate-count="b.auditCandidateCount"
      :audit-kept-count="b.auditKeptCount"
      :audit-filtered-count="b.auditFilteredCount"
      :audit-inactive-filtered-count="b.auditInactiveFilteredCount"
      :audit-older-version-filtered-count="b.auditOlderVersionFilteredCount"
      :audit-source-groups="b.auditSourceGroups"
      :audit-chunk-label="b.auditChunkLabel"
    />
  </div>
</template>
